/*

 TESTTILESMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\c\test\tiles\gbTilesTest.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define TestTilesMapWidth 20
#define TestTilesMapHeight 18
#define TestTilesMapBank 0

extern unsigned char TestTilesMap[];

/* End of TESTTILESMAP.H */
